apiVersion: apps/v1
kind: Deployment
metadata:
  name: raju-new
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: raju-new
  template:
    metadata:
      labels:
        app: raju-new
    spec:
      containers:
      - name: raju-new
        image: nginx:latest
        ports:
        - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx-service1
  namespace: default
spec:
  selector:
    app: raju-new
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
  type: LoadBalancer
