apiVersion: apps/v1
kind: Deployment
metadata:
  name: raju-app 
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: raju-app
  template:
    metadata:
      labels:
        app: raju-app
    spec:
      containers:
      - name: raju-app
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx-service
  namespace: default
spec:
  selector:
    app: raju-app 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
